#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -N JVASP-1067
#PBS -o job.out
#PBS -e job.err
cd /users/knc6/Software/Devs/jarvis/docs/JVASP-1067_PBEBO
source ~/anaconda2/envs/my_jarvis/bin/activate my_jarvis 
python job_fact.py
