#!/bin/bash
#PBS -N MAIN-BAND-bulk@mp_149
#PBS -l walltime=148:10:00
#PBS -o test.log
#PBS -m abe
#PBS -j oe
#PBS -r n
#PBS -l nodes=8:ppn=2
#PBS -l pmem=1500
mpirun -np 16 /users/knc6/bin/vasp_5.3.3_parallel >vasp.out
