#!/bin/bash
#PBS -N Si-v
#PBS -o test.log
#PBS -l nodes=1:ppn=24

# VASP_PSP_DIR and vasp_bulk_exe must be changed

cd /rk2/knc6/GASP/Si-vasp

export PATH=/users/knc6/bin:$PATH
export VASP_PSP_DIR=/home/knc6/Software/VASP-POTENTIAL
export vasp_bulk_exe=/users/knc6/VASP/vasp54/src/vasp.5.4.1Dobby/bin/vasp_std
export vasp_surf_exe= /users/knc6/VASP/vasp54/src/vasp.5.4.1/bin/vasp_std
export vasp_nw_exe= /users/knc6/VASP/vasp54/src/vasp.5.4.1/bin/vasp_std
export vasp_soc_exe= /users/knc6/VASP/vasp54/src/vasp.5.4.1/bin/vasp_std
export vasp_pot_yaml=/users/knc6/bin/Special_POTCAR.yaml
export vasp_vdw_dat=/users/knc6/bin/vdw_kernel.bindat
export mp_json='/users/knc6/bin/r.json'

source /users/knc6/anaconda2/envs/my_gasp/bin/activate my_gasp

run.py ga_input.yaml 2>&1 | tee ga_output
