#!/bin/bash
# script to run lammps
# usage: calllammps /path/to/lammps/input/file

# get the name of the input file, without the path
input_file=$(basename $1)

# get the path to the job directory containing the input file
dir_path=$(dirname $1)

# move into the job directory
cd $dir_path

# run lammps on the input file
/users/knc6/Software/LAMMPS/lammps-master/src/lmp_serial < $input_file
