#!/bin/bash
#PBS -N KPOINTSbulk@mp_149-45
#PBS -l walltime=148:10:00
#PBS -o test.log
#PBS -m abe
#PBS -j oe
#PBS -r n
#PBS -l nodes=8:ppn=2
#PBS -l pmem=1500
cd /data/knc6/NIST4/Elements-bulkk/mp-149_bulk_PBEBO/KPOINTSbulk@mp_149-45
mpirun -np 16 /users/knc6/bin/vasp_5.3.3_parallel >vasp.out
