#!/bin/bash
#PBS -N si
#PBS -o test.log
#PBS -m abe
#PBS -j oe
#PBS -r n
#PBS -l nodes=1:ppn=16
cd /rk2/knc6/test
export VASP_PSP_DIR=/users/knc6/VASP/VASP-POTENTIAL


export PATH=/users/knc6/bin:$PATH
export vasp_bulk_exe=/users/knc6/VASP/vasp54/src/vasp.5.4.1Dobby/bin/vasp_std
export vasp_surf_exe=/users/knc6/VASP/vasp54/src/vasp.5.4.1Dobbynoz/bin/vasp_std
export vasp_nw_exe=/users/knc6/VASP/vasp54/src/vasp.5.4.1Dobbynoz/bin/vasp_std
export vasp_soc_exe=/users/knc6/VASP/vasp54/src/vasp.5.4.1Dobby/bin/vasp_ncl
export vasp_pot_yaml=/users/knc6/bin/Special_POTCAR.yaml
export vasp_vdw_dat=/users/knc6/bin/vdw_kernel.bindat
export mp_json='/home/knc6/bin/MPall_datacopy.json'
python j_pyvasp.py

